### PR TITLE
Command update on redme doc

### PR DESCRIPTION
**Pull request by imbakar**
Command update with terminal compatibility

### CODE REVIEW

**Comment by khelle** [comment]
Using php prefix is not needed when environment is set properly. What's more, everywhere in shown examples each command is already written without php prefix. Does this change benefits the docs ? I believe the emphasis should be rather on adding info box, that on some configuration prefixing the commands with `php` binary is required.

**Comment by imbakar** [comment]
If `php` is added before the command it will be easier to understand. First I run `kraken.server` and got an error then try `php kraken.server` and work. So I think for all levels of programmers adding  `php`  will better

**Comment by khelle** [comment]
Seems fair. I will accept this PR if you create similar for demo-chat repository.

**Comment by imbakar** [comment]
I already did !
But you can request to do that, but you add a condition!

Is there any way to run the app like normal php style throw Apache ?

**Comment by khelle** [comment]
Not really. The whole point of this project is to daemonize and distribute php backend in agent-based, async & supervised architecture. It is not another MVC framework to be put behind apache.

**Pull request merged**
